{% set name = "adl2pydm" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/adl2pydm-{{ version }}.tar.gz
  sha256: 37d698b523d6f5b1fcef4a74081314950d69b3aaa83e3c6e682e6b6e6b5e89a9

build:
  entry_points:
    - adl2pydm = adl2pydm.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - adl2pydm
  commands:
    - pip check
    - adl2pydm --help
  requires:
    - pip

about:
  home: https://github.com/BCDA-APS/adl2pydm
  summary: Convert MEDM's .adl files to PyDM's .ui format.
  license: BSD-4-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - prjemian
